// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using REST_API_Granja.Data;

#nullable disable

namespace REST_API_Granja.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20240917010144_AddDataIntoAnimals")]
    partial class AddDataIntoAnimals
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("REST_API_Granja.Models.Animal", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AnimalTypeId")
                        .HasColumnType("int")
                        .HasColumnName("animal_type_id");

                    b.Property<DateOnly?>("BirthDate")
                        .HasColumnType("date")
                        .HasColumnName("birth_date");

                    b.Property<string>("Description")
                        .HasMaxLength(250)
                        .HasColumnType("varchar(250)")
                        .HasColumnName("description");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("name");

                    b.Property<double?>("WeightKg")
                        .HasColumnType("double")
                        .HasColumnName("weight");

                    b.HasKey("Id");

                    b.HasIndex("AnimalTypeId");

                    b.ToTable("animals");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AnimalTypeId = 4,
                            BirthDate = new DateOnly(2022, 1, 5),
                            Description = "New ABC 13 9370, 13.3, 5th Gen CoreA5-8250U, 8GB RAM, 256GB SSD, power UHD Graphics, OS 10 Home, OS Office A & J 2016",
                            Name = "Ollie",
                            WeightKg = 293.7973014404393
                        },
                        new
                        {
                            Id = 2,
                            AnimalTypeId = 1,
                            BirthDate = new DateOnly(2024, 5, 18),
                            Description = "The Football Is Good For Training And Recreational Purposes",
                            Name = "Amanda",
                            WeightKg = 332.17163856618697
                        },
                        new
                        {
                            Id = 3,
                            AnimalTypeId = 3,
                            BirthDate = new DateOnly(2024, 7, 10),
                            Description = "Ergonomic executive chair upholstered in bonded black leather and PVC padded seat and back for all-day comfort and support",
                            Name = "Harvey",
                            WeightKg = 374.71158187741366
                        },
                        new
                        {
                            Id = 4,
                            AnimalTypeId = 4,
                            BirthDate = new DateOnly(2023, 5, 21),
                            Description = "The Nagasaki Lander is the trademarked name of several series of Nagasaki sport bikes, that started with the 1984 ABC800J",
                            Name = "Larry",
                            WeightKg = 356.00452392771984
                        },
                        new
                        {
                            Id = 5,
                            AnimalTypeId = 4,
                            BirthDate = new DateOnly(2024, 7, 11),
                            Description = "New ABC 13 9370, 13.3, 5th Gen CoreA5-8250U, 8GB RAM, 256GB SSD, power UHD Graphics, OS 10 Home, OS Office A & J 2016",
                            Name = "John",
                            WeightKg = 247.12386811282988
                        },
                        new
                        {
                            Id = 6,
                            AnimalTypeId = 4,
                            BirthDate = new DateOnly(2022, 9, 23),
                            Description = "The beautiful range of Apple Naturalé that has an exciting mix of natural ingredients. With the Goodness of 100% Natural Ingredients",
                            Name = "Hugo",
                            WeightKg = 337.32125174467268
                        },
                        new
                        {
                            Id = 7,
                            AnimalTypeId = 2,
                            BirthDate = new DateOnly(2022, 11, 28),
                            Description = "New range of formal shirts are designed keeping you in mind. With fits and styling that will make you stand apart",
                            Name = "Nick",
                            WeightKg = 43.105309543220663
                        },
                        new
                        {
                            Id = 8,
                            AnimalTypeId = 3,
                            BirthDate = new DateOnly(2024, 8, 27),
                            Description = "New range of formal shirts are designed keeping you in mind. With fits and styling that will make you stand apart",
                            Name = "Muriel",
                            WeightKg = 185.87962608364876
                        },
                        new
                        {
                            Id = 9,
                            AnimalTypeId = 3,
                            BirthDate = new DateOnly(2020, 4, 17),
                            Description = "The Nagasaki Lander is the trademarked name of several series of Nagasaki sport bikes, that started with the 1984 ABC800J",
                            Name = "Matt",
                            WeightKg = 159.57788283744219
                        },
                        new
                        {
                            Id = 10,
                            AnimalTypeId = 5,
                            BirthDate = new DateOnly(2022, 6, 6),
                            Description = "The Apollotech B340 is an affordable wireless mouse with reliable connectivity, 12 months battery life and modern design",
                            Name = "Jason",
                            WeightKg = 296.45683235562802
                        },
                        new
                        {
                            Id = 11,
                            AnimalTypeId = 1,
                            BirthDate = new DateOnly(2023, 7, 14),
                            Description = "The Football Is Good For Training And Recreational Purposes",
                            Name = "Andre",
                            WeightKg = 210.54372118298562
                        },
                        new
                        {
                            Id = 12,
                            AnimalTypeId = 1,
                            BirthDate = new DateOnly(2024, 1, 8),
                            Description = "Carbonite web goalkeeper gloves are ergonomically designed to give easy fit",
                            Name = "Chester",
                            WeightKg = 139.94336586356246
                        },
                        new
                        {
                            Id = 13,
                            AnimalTypeId = 5,
                            BirthDate = new DateOnly(2024, 9, 14),
                            Description = "The Apollotech B340 is an affordable wireless mouse with reliable connectivity, 12 months battery life and modern design",
                            Name = "Philip",
                            WeightKg = 21.098943145960352
                        },
                        new
                        {
                            Id = 14,
                            AnimalTypeId = 3,
                            BirthDate = new DateOnly(2023, 10, 27),
                            Description = "The Football Is Good For Training And Recreational Purposes",
                            Name = "Ruben",
                            WeightKg = 283.2364211557134
                        },
                        new
                        {
                            Id = 15,
                            AnimalTypeId = 1,
                            BirthDate = new DateOnly(2019, 12, 22),
                            Description = "Boston's most advanced compression wear technology increases muscle oxygenation, stabilizes active muscles",
                            Name = "Jacqueline",
                            WeightKg = 213.64281958575819
                        },
                        new
                        {
                            Id = 16,
                            AnimalTypeId = 1,
                            BirthDate = new DateOnly(2021, 7, 14),
                            Description = "Andy shoes are designed to keeping in mind durability as well as trends, the most stylish range of shoes & sandals",
                            Name = "Mandy",
                            WeightKg = 31.200976668720891
                        },
                        new
                        {
                            Id = 17,
                            AnimalTypeId = 1,
                            BirthDate = new DateOnly(2024, 8, 10),
                            Description = "The Apollotech B340 is an affordable wireless mouse with reliable connectivity, 12 months battery life and modern design",
                            Name = "Megan",
                            WeightKg = 93.285013891497471
                        },
                        new
                        {
                            Id = 18,
                            AnimalTypeId = 5,
                            BirthDate = new DateOnly(2020, 11, 28),
                            Description = "New range of formal shirts are designed keeping you in mind. With fits and styling that will make you stand apart",
                            Name = "Alicia",
                            WeightKg = 277.35074740780624
                        },
                        new
                        {
                            Id = 19,
                            AnimalTypeId = 5,
                            BirthDate = new DateOnly(2022, 4, 11),
                            Description = "The Nagasaki Lander is the trademarked name of several series of Nagasaki sport bikes, that started with the 1984 ABC800J",
                            Name = "Lee",
                            WeightKg = 90.796512734094463
                        },
                        new
                        {
                            Id = 20,
                            AnimalTypeId = 3,
                            BirthDate = new DateOnly(2020, 3, 1),
                            Description = "The slim & simple Maple Gaming Keyboard from Dev Byte comes with a sleek body and 7- Color RGB LED Back-lighting for smart functionality",
                            Name = "Adrienne",
                            WeightKg = 341.36072230914334
                        },
                        new
                        {
                            Id = 21,
                            AnimalTypeId = 4,
                            BirthDate = new DateOnly(2021, 10, 20),
                            Description = "The Apollotech B340 is an affordable wireless mouse with reliable connectivity, 12 months battery life and modern design",
                            Name = "Kristy",
                            WeightKg = 413.86332798547784
                        },
                        new
                        {
                            Id = 22,
                            AnimalTypeId = 1,
                            BirthDate = new DateOnly(2023, 6, 29),
                            Description = "New range of formal shirts are designed keeping you in mind. With fits and styling that will make you stand apart",
                            Name = "Kim",
                            WeightKg = 234.29052886978755
                        },
                        new
                        {
                            Id = 23,
                            AnimalTypeId = 5,
                            BirthDate = new DateOnly(2020, 6, 17),
                            Description = "Carbonite web goalkeeper gloves are ergonomically designed to give easy fit",
                            Name = "Cindy",
                            WeightKg = 106.82825546323501
                        },
                        new
                        {
                            Id = 24,
                            AnimalTypeId = 6,
                            BirthDate = new DateOnly(2023, 5, 6),
                            Description = "New range of formal shirts are designed keeping you in mind. With fits and styling that will make you stand apart",
                            Name = "Alyssa",
                            WeightKg = 13.718521768423905
                        },
                        new
                        {
                            Id = 25,
                            AnimalTypeId = 2,
                            BirthDate = new DateOnly(2021, 5, 14),
                            Description = "The slim & simple Maple Gaming Keyboard from Dev Byte comes with a sleek body and 7- Color RGB LED Back-lighting for smart functionality",
                            Name = "Irene",
                            WeightKg = 155.45105690389332
                        },
                        new
                        {
                            Id = 26,
                            AnimalTypeId = 5,
                            BirthDate = new DateOnly(2024, 9, 15),
                            Description = "The slim & simple Maple Gaming Keyboard from Dev Byte comes with a sleek body and 7- Color RGB LED Back-lighting for smart functionality",
                            Name = "Ervin",
                            WeightKg = 361.84834718337493
                        },
                        new
                        {
                            Id = 27,
                            AnimalTypeId = 6,
                            BirthDate = new DateOnly(2023, 5, 2),
                            Description = "The beautiful range of Apple Naturalé that has an exciting mix of natural ingredients. With the Goodness of 100% Natural Ingredients",
                            Name = "Claudia",
                            WeightKg = 46.607295115430496
                        },
                        new
                        {
                            Id = 28,
                            AnimalTypeId = 4,
                            BirthDate = new DateOnly(2019, 11, 1),
                            Description = "The slim & simple Maple Gaming Keyboard from Dev Byte comes with a sleek body and 7- Color RGB LED Back-lighting for smart functionality",
                            Name = "Tami",
                            WeightKg = 437.94569997075723
                        },
                        new
                        {
                            Id = 29,
                            AnimalTypeId = 3,
                            BirthDate = new DateOnly(2022, 7, 29),
                            Description = "New ABC 13 9370, 13.3, 5th Gen CoreA5-8250U, 8GB RAM, 256GB SSD, power UHD Graphics, OS 10 Home, OS Office A & J 2016",
                            Name = "Pat",
                            WeightKg = 413.59978226700684
                        },
                        new
                        {
                            Id = 30,
                            AnimalTypeId = 5,
                            BirthDate = new DateOnly(2023, 9, 10),
                            Description = "The Nagasaki Lander is the trademarked name of several series of Nagasaki sport bikes, that started with the 1984 ABC800J",
                            Name = "Nettie",
                            WeightKg = 357.27053250944164
                        },
                        new
                        {
                            Id = 31,
                            AnimalTypeId = 1,
                            BirthDate = new DateOnly(2024, 6, 19),
                            Description = "New ABC 13 9370, 13.3, 5th Gen CoreA5-8250U, 8GB RAM, 256GB SSD, power UHD Graphics, OS 10 Home, OS Office A & J 2016",
                            Name = "Delores",
                            WeightKg = 493.66253488053883
                        },
                        new
                        {
                            Id = 32,
                            AnimalTypeId = 6,
                            BirthDate = new DateOnly(2023, 3, 25),
                            Description = "Andy shoes are designed to keeping in mind durability as well as trends, the most stylish range of shoes & sandals",
                            Name = "Francis",
                            WeightKg = 434.99477921699207
                        },
                        new
                        {
                            Id = 33,
                            AnimalTypeId = 6,
                            BirthDate = new DateOnly(2020, 3, 19),
                            Description = "New ABC 13 9370, 13.3, 5th Gen CoreA5-8250U, 8GB RAM, 256GB SSD, power UHD Graphics, OS 10 Home, OS Office A & J 2016",
                            Name = "Wesley",
                            WeightKg = 452.2462752040326
                        },
                        new
                        {
                            Id = 34,
                            AnimalTypeId = 5,
                            BirthDate = new DateOnly(2020, 1, 2),
                            Description = "The Nagasaki Lander is the trademarked name of several series of Nagasaki sport bikes, that started with the 1984 ABC800J",
                            Name = "Ann",
                            WeightKg = 152.25400880504952
                        },
                        new
                        {
                            Id = 35,
                            AnimalTypeId = 4,
                            BirthDate = new DateOnly(2023, 7, 16),
                            Description = "The Apollotech B340 is an affordable wireless mouse with reliable connectivity, 12 months battery life and modern design",
                            Name = "Rudy",
                            WeightKg = 181.09067889949981
                        },
                        new
                        {
                            Id = 36,
                            AnimalTypeId = 6,
                            BirthDate = new DateOnly(2021, 7, 8),
                            Description = "Ergonomic executive chair upholstered in bonded black leather and PVC padded seat and back for all-day comfort and support",
                            Name = "Spencer",
                            WeightKg = 490.95193634443223
                        },
                        new
                        {
                            Id = 37,
                            AnimalTypeId = 2,
                            BirthDate = new DateOnly(2019, 10, 12),
                            Description = "Ergonomic executive chair upholstered in bonded black leather and PVC padded seat and back for all-day comfort and support",
                            Name = "Marianne",
                            WeightKg = 107.0417348387025
                        },
                        new
                        {
                            Id = 38,
                            AnimalTypeId = 6,
                            BirthDate = new DateOnly(2021, 7, 26),
                            Description = "Ergonomic executive chair upholstered in bonded black leather and PVC padded seat and back for all-day comfort and support",
                            Name = "Ben",
                            WeightKg = 165.1215694884491
                        },
                        new
                        {
                            Id = 39,
                            AnimalTypeId = 6,
                            BirthDate = new DateOnly(2020, 3, 10),
                            Description = "Boston's most advanced compression wear technology increases muscle oxygenation, stabilizes active muscles",
                            Name = "Angelo",
                            WeightKg = 155.69868437644652
                        },
                        new
                        {
                            Id = 40,
                            AnimalTypeId = 3,
                            BirthDate = new DateOnly(2021, 2, 14),
                            Description = "Ergonomic executive chair upholstered in bonded black leather and PVC padded seat and back for all-day comfort and support",
                            Name = "Stacy",
                            WeightKg = 106.91893422298362
                        },
                        new
                        {
                            Id = 41,
                            AnimalTypeId = 2,
                            BirthDate = new DateOnly(2021, 5, 3),
                            Description = "The beautiful range of Apple Naturalé that has an exciting mix of natural ingredients. With the Goodness of 100% Natural Ingredients",
                            Name = "Doris",
                            WeightKg = 139.07537468862674
                        },
                        new
                        {
                            Id = 42,
                            AnimalTypeId = 3,
                            BirthDate = new DateOnly(2022, 4, 14),
                            Description = "The Apollotech B340 is an affordable wireless mouse with reliable connectivity, 12 months battery life and modern design",
                            Name = "Edmond",
                            WeightKg = 436.6806781209965
                        },
                        new
                        {
                            Id = 43,
                            AnimalTypeId = 6,
                            BirthDate = new DateOnly(2023, 10, 24),
                            Description = "Andy shoes are designed to keeping in mind durability as well as trends, the most stylish range of shoes & sandals",
                            Name = "Terri",
                            WeightKg = 453.07952353716291
                        },
                        new
                        {
                            Id = 44,
                            AnimalTypeId = 3,
                            BirthDate = new DateOnly(2020, 11, 28),
                            Description = "The Apollotech B340 is an affordable wireless mouse with reliable connectivity, 12 months battery life and modern design",
                            Name = "Hubert",
                            WeightKg = 340.83078230458153
                        },
                        new
                        {
                            Id = 45,
                            AnimalTypeId = 3,
                            BirthDate = new DateOnly(2020, 8, 24),
                            Description = "The slim & simple Maple Gaming Keyboard from Dev Byte comes with a sleek body and 7- Color RGB LED Back-lighting for smart functionality",
                            Name = "Gail",
                            WeightKg = 33.533899742361939
                        },
                        new
                        {
                            Id = 46,
                            AnimalTypeId = 3,
                            BirthDate = new DateOnly(2021, 6, 5),
                            Description = "Boston's most advanced compression wear technology increases muscle oxygenation, stabilizes active muscles",
                            Name = "Cora",
                            WeightKg = 71.683362006218644
                        },
                        new
                        {
                            Id = 47,
                            AnimalTypeId = 6,
                            BirthDate = new DateOnly(2021, 4, 13),
                            Description = "Boston's most advanced compression wear technology increases muscle oxygenation, stabilizes active muscles",
                            Name = "Blanca",
                            WeightKg = 57.38429582765729
                        },
                        new
                        {
                            Id = 48,
                            AnimalTypeId = 4,
                            BirthDate = new DateOnly(2021, 9, 12),
                            Description = "New range of formal shirts are designed keeping you in mind. With fits and styling that will make you stand apart",
                            Name = "Evelyn",
                            WeightKg = 189.25031721544752
                        },
                        new
                        {
                            Id = 49,
                            AnimalTypeId = 4,
                            BirthDate = new DateOnly(2024, 3, 14),
                            Description = "The automobile layout consists of a front-engine design, with transaxle-type transmissions mounted at the rear of the engine and four wheel drive",
                            Name = "Barry",
                            WeightKg = 33.186933032504371
                        },
                        new
                        {
                            Id = 50,
                            AnimalTypeId = 5,
                            BirthDate = new DateOnly(2024, 6, 10),
                            Description = "The Football Is Good For Training And Recreational Purposes",
                            Name = "Katherine",
                            WeightKg = 443.56203472044956
                        },
                        new
                        {
                            Id = 51,
                            AnimalTypeId = 2,
                            BirthDate = new DateOnly(2021, 9, 23),
                            Description = "The slim & simple Maple Gaming Keyboard from Dev Byte comes with a sleek body and 7- Color RGB LED Back-lighting for smart functionality",
                            Name = "Alan",
                            WeightKg = 70.576470401986825
                        },
                        new
                        {
                            Id = 52,
                            AnimalTypeId = 2,
                            BirthDate = new DateOnly(2021, 1, 28),
                            Description = "Carbonite web goalkeeper gloves are ergonomically designed to give easy fit",
                            Name = "Jerome",
                            WeightKg = 472.38455528456842
                        },
                        new
                        {
                            Id = 53,
                            AnimalTypeId = 6,
                            BirthDate = new DateOnly(2023, 10, 3),
                            Description = "Carbonite web goalkeeper gloves are ergonomically designed to give easy fit",
                            Name = "Terry",
                            WeightKg = 456.65343463736957
                        },
                        new
                        {
                            Id = 54,
                            AnimalTypeId = 4,
                            BirthDate = new DateOnly(2023, 6, 8),
                            Description = "Boston's most advanced compression wear technology increases muscle oxygenation, stabilizes active muscles",
                            Name = "Lynne",
                            WeightKg = 250.46686030756209
                        },
                        new
                        {
                            Id = 55,
                            AnimalTypeId = 6,
                            BirthDate = new DateOnly(2023, 2, 8),
                            Description = "The automobile layout consists of a front-engine design, with transaxle-type transmissions mounted at the rear of the engine and four wheel drive",
                            Name = "Glen",
                            WeightKg = 76.837791496312533
                        },
                        new
                        {
                            Id = 56,
                            AnimalTypeId = 6,
                            BirthDate = new DateOnly(2024, 1, 26),
                            Description = "The slim & simple Maple Gaming Keyboard from Dev Byte comes with a sleek body and 7- Color RGB LED Back-lighting for smart functionality",
                            Name = "Rachel",
                            WeightKg = 135.64367119319556
                        },
                        new
                        {
                            Id = 57,
                            AnimalTypeId = 2,
                            BirthDate = new DateOnly(2021, 10, 12),
                            Description = "Ergonomic executive chair upholstered in bonded black leather and PVC padded seat and back for all-day comfort and support",
                            Name = "Yvette",
                            WeightKg = 11.080546173714456
                        },
                        new
                        {
                            Id = 58,
                            AnimalTypeId = 6,
                            BirthDate = new DateOnly(2022, 12, 1),
                            Description = "Boston's most advanced compression wear technology increases muscle oxygenation, stabilizes active muscles",
                            Name = "Leigh",
                            WeightKg = 421.4746989813645
                        },
                        new
                        {
                            Id = 59,
                            AnimalTypeId = 4,
                            BirthDate = new DateOnly(2022, 8, 9),
                            Description = "The Nagasaki Lander is the trademarked name of several series of Nagasaki sport bikes, that started with the 1984 ABC800J",
                            Name = "Edna",
                            WeightKg = 305.76301728708393
                        },
                        new
                        {
                            Id = 60,
                            AnimalTypeId = 6,
                            BirthDate = new DateOnly(2024, 4, 12),
                            Description = "The beautiful range of Apple Naturalé that has an exciting mix of natural ingredients. With the Goodness of 100% Natural Ingredients",
                            Name = "Emilio",
                            WeightKg = 264.18235832223468
                        },
                        new
                        {
                            Id = 61,
                            AnimalTypeId = 6,
                            BirthDate = new DateOnly(2024, 1, 4),
                            Description = "New range of formal shirts are designed keeping you in mind. With fits and styling that will make you stand apart",
                            Name = "Claudia",
                            WeightKg = 20.013440664746454
                        },
                        new
                        {
                            Id = 62,
                            AnimalTypeId = 5,
                            BirthDate = new DateOnly(2021, 12, 27),
                            Description = "The Football Is Good For Training And Recreational Purposes",
                            Name = "Felipe",
                            WeightKg = 201.19250251100794
                        },
                        new
                        {
                            Id = 63,
                            AnimalTypeId = 3,
                            BirthDate = new DateOnly(2021, 10, 29),
                            Description = "The slim & simple Maple Gaming Keyboard from Dev Byte comes with a sleek body and 7- Color RGB LED Back-lighting for smart functionality",
                            Name = "Emily",
                            WeightKg = 77.162389097345908
                        },
                        new
                        {
                            Id = 64,
                            AnimalTypeId = 5,
                            BirthDate = new DateOnly(2022, 5, 30),
                            Description = "The Apollotech B340 is an affordable wireless mouse with reliable connectivity, 12 months battery life and modern design",
                            Name = "Julia",
                            WeightKg = 384.33708361664378
                        },
                        new
                        {
                            Id = 65,
                            AnimalTypeId = 3,
                            BirthDate = new DateOnly(2020, 1, 6),
                            Description = "The automobile layout consists of a front-engine design, with transaxle-type transmissions mounted at the rear of the engine and four wheel drive",
                            Name = "Natalie",
                            WeightKg = 343.78291347547207
                        },
                        new
                        {
                            Id = 66,
                            AnimalTypeId = 5,
                            BirthDate = new DateOnly(2022, 6, 30),
                            Description = "The Nagasaki Lander is the trademarked name of several series of Nagasaki sport bikes, that started with the 1984 ABC800J",
                            Name = "Dolores",
                            WeightKg = 334.0107763014575
                        },
                        new
                        {
                            Id = 67,
                            AnimalTypeId = 1,
                            BirthDate = new DateOnly(2019, 11, 11),
                            Description = "New range of formal shirts are designed keeping you in mind. With fits and styling that will make you stand apart",
                            Name = "Gerardo",
                            WeightKg = 476.29008275062745
                        },
                        new
                        {
                            Id = 68,
                            AnimalTypeId = 3,
                            BirthDate = new DateOnly(2021, 4, 25),
                            Description = "The automobile layout consists of a front-engine design, with transaxle-type transmissions mounted at the rear of the engine and four wheel drive",
                            Name = "Rose",
                            WeightKg = 326.8456448315888
                        },
                        new
                        {
                            Id = 69,
                            AnimalTypeId = 5,
                            BirthDate = new DateOnly(2023, 8, 28),
                            Description = "Carbonite web goalkeeper gloves are ergonomically designed to give easy fit",
                            Name = "Alyssa",
                            WeightKg = 229.34105522879301
                        },
                        new
                        {
                            Id = 70,
                            AnimalTypeId = 3,
                            BirthDate = new DateOnly(2023, 6, 2),
                            Description = "The Football Is Good For Training And Recreational Purposes",
                            Name = "Fredrick",
                            WeightKg = 24.510554021288783
                        },
                        new
                        {
                            Id = 71,
                            AnimalTypeId = 6,
                            BirthDate = new DateOnly(2021, 9, 30),
                            Description = "Boston's most advanced compression wear technology increases muscle oxygenation, stabilizes active muscles",
                            Name = "Jody",
                            WeightKg = 73.762731480712262
                        },
                        new
                        {
                            Id = 72,
                            AnimalTypeId = 2,
                            BirthDate = new DateOnly(2024, 3, 10),
                            Description = "Ergonomic executive chair upholstered in bonded black leather and PVC padded seat and back for all-day comfort and support",
                            Name = "Forrest",
                            WeightKg = 76.708874915023529
                        },
                        new
                        {
                            Id = 73,
                            AnimalTypeId = 2,
                            BirthDate = new DateOnly(2021, 9, 7),
                            Description = "New range of formal shirts are designed keeping you in mind. With fits and styling that will make you stand apart",
                            Name = "Abel",
                            WeightKg = 8.8582884767623717
                        },
                        new
                        {
                            Id = 74,
                            AnimalTypeId = 5,
                            BirthDate = new DateOnly(2023, 8, 18),
                            Description = "New range of formal shirts are designed keeping you in mind. With fits and styling that will make you stand apart",
                            Name = "Jenny",
                            WeightKg = 58.995061097295149
                        },
                        new
                        {
                            Id = 75,
                            AnimalTypeId = 1,
                            BirthDate = new DateOnly(2023, 3, 20),
                            Description = "New range of formal shirts are designed keeping you in mind. With fits and styling that will make you stand apart",
                            Name = "Jeannette",
                            WeightKg = 221.63005748806518
                        },
                        new
                        {
                            Id = 76,
                            AnimalTypeId = 6,
                            BirthDate = new DateOnly(2020, 12, 25),
                            Description = "Carbonite web goalkeeper gloves are ergonomically designed to give easy fit",
                            Name = "Boyd",
                            WeightKg = 163.53868934638223
                        },
                        new
                        {
                            Id = 77,
                            AnimalTypeId = 5,
                            BirthDate = new DateOnly(2024, 7, 27),
                            Description = "The Apollotech B340 is an affordable wireless mouse with reliable connectivity, 12 months battery life and modern design",
                            Name = "Tom",
                            WeightKg = 85.738427276724863
                        },
                        new
                        {
                            Id = 78,
                            AnimalTypeId = 2,
                            BirthDate = new DateOnly(2020, 1, 19),
                            Description = "New range of formal shirts are designed keeping you in mind. With fits and styling that will make you stand apart",
                            Name = "Brandi",
                            WeightKg = 222.79493632218109
                        },
                        new
                        {
                            Id = 79,
                            AnimalTypeId = 3,
                            BirthDate = new DateOnly(2024, 1, 8),
                            Description = "Boston's most advanced compression wear technology increases muscle oxygenation, stabilizes active muscles",
                            Name = "Lori",
                            WeightKg = 242.73220966436793
                        },
                        new
                        {
                            Id = 80,
                            AnimalTypeId = 3,
                            BirthDate = new DateOnly(2023, 7, 8),
                            Description = "Ergonomic executive chair upholstered in bonded black leather and PVC padded seat and back for all-day comfort and support",
                            Name = "Dianne",
                            WeightKg = 193.84468040359982
                        },
                        new
                        {
                            Id = 81,
                            AnimalTypeId = 3,
                            BirthDate = new DateOnly(2024, 8, 26),
                            Description = "New ABC 13 9370, 13.3, 5th Gen CoreA5-8250U, 8GB RAM, 256GB SSD, power UHD Graphics, OS 10 Home, OS Office A & J 2016",
                            Name = "Pamela",
                            WeightKg = 118.50788132141994
                        },
                        new
                        {
                            Id = 82,
                            AnimalTypeId = 4,
                            BirthDate = new DateOnly(2021, 12, 23),
                            Description = "Andy shoes are designed to keeping in mind durability as well as trends, the most stylish range of shoes & sandals",
                            Name = "Isabel",
                            WeightKg = 421.14557674448878
                        },
                        new
                        {
                            Id = 83,
                            AnimalTypeId = 3,
                            BirthDate = new DateOnly(2023, 5, 7),
                            Description = "The Apollotech B340 is an affordable wireless mouse with reliable connectivity, 12 months battery life and modern design",
                            Name = "Kelly",
                            WeightKg = 356.29468822127006
                        },
                        new
                        {
                            Id = 84,
                            AnimalTypeId = 6,
                            BirthDate = new DateOnly(2022, 2, 1),
                            Description = "The automobile layout consists of a front-engine design, with transaxle-type transmissions mounted at the rear of the engine and four wheel drive",
                            Name = "Sonya",
                            WeightKg = 370.38787282740776
                        },
                        new
                        {
                            Id = 85,
                            AnimalTypeId = 5,
                            BirthDate = new DateOnly(2019, 10, 20),
                            Description = "New ABC 13 9370, 13.3, 5th Gen CoreA5-8250U, 8GB RAM, 256GB SSD, power UHD Graphics, OS 10 Home, OS Office A & J 2016",
                            Name = "Hope",
                            WeightKg = 163.57010049226687
                        },
                        new
                        {
                            Id = 86,
                            AnimalTypeId = 6,
                            BirthDate = new DateOnly(2019, 10, 29),
                            Description = "Carbonite web goalkeeper gloves are ergonomically designed to give easy fit",
                            Name = "Ebony",
                            WeightKg = 350.28724211631709
                        },
                        new
                        {
                            Id = 87,
                            AnimalTypeId = 6,
                            BirthDate = new DateOnly(2021, 6, 27),
                            Description = "The slim & simple Maple Gaming Keyboard from Dev Byte comes with a sleek body and 7- Color RGB LED Back-lighting for smart functionality",
                            Name = "Neal",
                            WeightKg = 262.49627534555395
                        },
                        new
                        {
                            Id = 88,
                            AnimalTypeId = 4,
                            BirthDate = new DateOnly(2024, 7, 12),
                            Description = "New range of formal shirts are designed keeping you in mind. With fits and styling that will make you stand apart",
                            Name = "Hubert",
                            WeightKg = 382.01056503540565
                        },
                        new
                        {
                            Id = 89,
                            AnimalTypeId = 4,
                            BirthDate = new DateOnly(2022, 4, 23),
                            Description = "The automobile layout consists of a front-engine design, with transaxle-type transmissions mounted at the rear of the engine and four wheel drive",
                            Name = "Johnnie",
                            WeightKg = 162.096291203025
                        },
                        new
                        {
                            Id = 90,
                            AnimalTypeId = 3,
                            BirthDate = new DateOnly(2022, 11, 25),
                            Description = "Ergonomic executive chair upholstered in bonded black leather and PVC padded seat and back for all-day comfort and support",
                            Name = "Ada",
                            WeightKg = 467.86926021921715
                        },
                        new
                        {
                            Id = 91,
                            AnimalTypeId = 5,
                            BirthDate = new DateOnly(2022, 8, 5),
                            Description = "The beautiful range of Apple Naturalé that has an exciting mix of natural ingredients. With the Goodness of 100% Natural Ingredients",
                            Name = "Chelsea",
                            WeightKg = 441.45448922630948
                        },
                        new
                        {
                            Id = 92,
                            AnimalTypeId = 4,
                            BirthDate = new DateOnly(2021, 5, 15),
                            Description = "The Nagasaki Lander is the trademarked name of several series of Nagasaki sport bikes, that started with the 1984 ABC800J",
                            Name = "Tony",
                            WeightKg = 385.88963617411321
                        },
                        new
                        {
                            Id = 93,
                            AnimalTypeId = 5,
                            BirthDate = new DateOnly(2023, 3, 17),
                            Description = "Ergonomic executive chair upholstered in bonded black leather and PVC padded seat and back for all-day comfort and support",
                            Name = "Jeannette",
                            WeightKg = 380.88203622143828
                        },
                        new
                        {
                            Id = 94,
                            AnimalTypeId = 5,
                            BirthDate = new DateOnly(2023, 3, 28),
                            Description = "The slim & simple Maple Gaming Keyboard from Dev Byte comes with a sleek body and 7- Color RGB LED Back-lighting for smart functionality",
                            Name = "Joanna",
                            WeightKg = 171.12034153960528
                        },
                        new
                        {
                            Id = 95,
                            AnimalTypeId = 4,
                            BirthDate = new DateOnly(2023, 8, 4),
                            Description = "Boston's most advanced compression wear technology increases muscle oxygenation, stabilizes active muscles",
                            Name = "Emanuel",
                            WeightKg = 142.80587049728209
                        },
                        new
                        {
                            Id = 96,
                            AnimalTypeId = 6,
                            BirthDate = new DateOnly(2021, 7, 28),
                            Description = "The Nagasaki Lander is the trademarked name of several series of Nagasaki sport bikes, that started with the 1984 ABC800J",
                            Name = "Sean",
                            WeightKg = 388.57509736320782
                        },
                        new
                        {
                            Id = 97,
                            AnimalTypeId = 2,
                            BirthDate = new DateOnly(2021, 7, 17),
                            Description = "Andy shoes are designed to keeping in mind durability as well as trends, the most stylish range of shoes & sandals",
                            Name = "Kate",
                            WeightKg = 102.29664670410605
                        },
                        new
                        {
                            Id = 98,
                            AnimalTypeId = 1,
                            BirthDate = new DateOnly(2020, 3, 3),
                            Description = "The Football Is Good For Training And Recreational Purposes",
                            Name = "Leah",
                            WeightKg = 330.02663920455757
                        },
                        new
                        {
                            Id = 99,
                            AnimalTypeId = 2,
                            BirthDate = new DateOnly(2021, 4, 4),
                            Description = "Andy shoes are designed to keeping in mind durability as well as trends, the most stylish range of shoes & sandals",
                            Name = "Penny",
                            WeightKg = 322.12188647469674
                        },
                        new
                        {
                            Id = 100,
                            AnimalTypeId = 6,
                            BirthDate = new DateOnly(2024, 2, 7),
                            Description = "The beautiful range of Apple Naturalé that has an exciting mix of natural ingredients. With the Goodness of 100% Natural Ingredients",
                            Name = "Lucas",
                            WeightKg = 130.7458534043846
                        });
                });

            modelBuilder.Entity("REST_API_Granja.Models.AnimalType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasMaxLength(250)
                        .HasColumnType("varchar(250)")
                        .HasColumnName("description");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.ToTable("animal_types");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "vertebrados de sangre caliente con pelo o pelaje.",
                            Name = "mamífero"
                        },
                        new
                        {
                            Id = 2,
                            Description = "vertebrados emplumados y alados capaces de volar.",
                            Name = "ave"
                        },
                        new
                        {
                            Id = 3,
                            Description = "vertebrados de sangre fría con escamas.",
                            Name = "reptil"
                        },
                        new
                        {
                            Id = 4,
                            Description = "vertebrados de sangre fría que pasan parte de su vida en el agua y parte en tierra.",
                            Name = "anfibio"
                        },
                        new
                        {
                            Id = 5,
                            Description = "vertebrados acuáticos con branquias, aletas y escamas.",
                            Name = "pez"
                        },
                        new
                        {
                            Id = 6,
                            Description = "animales sin columna vertebral, incluyendo insectos, arañas y moluscos.",
                            Name = "invertebrado"
                        });
                });

            modelBuilder.Entity("REST_API_Granja.Models.Animal", b =>
                {
                    b.HasOne("REST_API_Granja.Models.AnimalType", "AnimalType")
                        .WithMany()
                        .HasForeignKey("AnimalTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AnimalType");
                });
#pragma warning restore 612, 618
        }
    }
}
